name: Verify website build

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: npm install & build
      run: |
        npm install
        npm run build
      env:
        CI: true