name: CI (Website)

# only run on pull_request events that target the master branch:
on:
  pull_request:
    branches:
    - master

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [10.x]
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - name: npm install, build
  #     run: |
  #       npm install
  #       npm run build
  #     env:
  #       CI: true
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run build
    - uses: seanmiddleditch/gha-publish-to-git@master
      with:
        branch: gh-pages
        github_token: '${{ secrets.ACT_R_PAT_TOKEN  }}'
        github_pat: '${{ secrets.ACT_R_PAT_TOKEN }}'
        source_folder: public
      if: success() && github.event == 'push'