name: Publish Website to ACT-Rules Repo

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: npm install & build
      run: |
        npm install
        npm run build
    - shell: bash
      run: |
        # set up git config
        git config user.name "${{ secrets.USER_NAME }}"
        git config user.email "${{ secrets.USER_EMAIL }}"

        # reset `package-lock.json`
        git checkout -- package-lock.json

        # add `act-rules-communuty` repo as a remote
        git remote add act-r-repo https://github.com/act-rules/act-rules.github.io

        # remove all files except the generated public directory and required git folders
        shopt -s extglob
        rm -rv !('public'|'.circleci'|'.git'|'.gitignore'|'node_modules')
        shopt -u extglob

        # move generated public in the root folder and remove the empty generated public folder
        mv public/* .
        rm -R public/

        # commit and push
        git add -fA
        git commit --allow-empty -m "update site [ci skip]"
        git push act-r-repo gh-pages --no-verify

