name: test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install NPM dependencies
        run: npm install

      - name: Build Gatsby website
        run: npm run build
        env:
          CI: true
