# This workflow ensures
# - that the Gatsby website can build
# ---
# It runs on every:
# - pull request that is opened to develop branch
name: test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          check-latest: true
      - uses: allenevans/set-env@v1.0.0
        with:
          GITHUB_USER_PERSONAL_ACCESS_TOKEN: ${{ secrets.USER_PAT }}
      - run: npm install
      - run: npm run lint
      - run: npm run build
