name: publish

on:
  repository_dispatch:
  push:
    branches:
      - build-tmp

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Publish website
        shell: bash
        run: |
          # git config
          git config user.name "${{ secrets.USER_NAME }}"
          git config user.email "${{ secrets.USER_EMAIL }}"

          # reset `package-lock.json`
          git checkout -- package-lock.json

          # add `act-rules-communuty` repo as a remote, get latest of master branch
          git remote add act-r-repo https://${{ secrets.USER_PAT }}@github.com/act-rules/act-rules.github.io
          git fetch act-r-repo jey
          git checkout act-r-repo/jey
          git pull act-r-repo jey

          touch jey.txt

          # commit and push to ACT R repositories master branch
          git add -fA
          git commit --allow-empty -m "update site from act-website repo"
          git push act-r-repo HEAD:refs/heads/jey --no-verify
